In [2]:
#numpy
import numpy as np

In [55]:
l1  = [1,2,3]
l2 = [4,5,6]
print(l1[:])

[1, 2, 3]


In [6]:
n1  =np.array(l1)
n2 = np.array(l2)
print(n1+n2)

[5 7 9]


In [9]:
l = [1,2,3,4,1.5]
arr = np.array(l)
print(arr)

[1.  2.  3.  4.  1.5]


In [15]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [45]:
n = np.array(matrix)
l = []
print(n)
print(n[:2,1:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [ ]:
for i in n:
    l.append(i.tolist())
print(l)

In [43]:
#arange

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [44]:
np.zeros(3)

array([0., 0., 0.])

In [47]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
# 3-d array
np.random.rand(2,2,2)

array([[[0.38087203, 0.41767272],
        [0.76316771, 0.32455216]],

       [[0.50699379, 0.00462191],
        [0.72732876, 0.2955362 ]]])

In [52]:
# 1-d array
np.random.rand(2)

array([0.2996708, 0.1730931])

In [53]:
np.random.randint(1,100,size = (3,3))

array([[24, 57, 86],
       [21, 10, 63],
       [48, 34, 48]], dtype=int32)

In [ ]:
#change a dimenshion of array
arr.reshape(25,1)

In [57]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
n = np.array(arr)
print(n[:2,1:])
print(n[1][0])

[[2 3]
 [5 6]]
4


In [62]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))
x4 = np.random.randint(10,size=(3,3,4,5))
print(x1)
print("2")
print(x2)
print("3")
print(x3)
print("4")
print(x4)

[0 4 0 7 6 0]
2
[[1 1 5 5]
 [8 6 2 8]
 [7 2 9 9]]
3
[[[3 4 0 1 9]
  [1 4 8 2 7]
  [7 6 4 5 5]
  [5 1 4 0 4]]

 [[5 2 8 5 2]
  [2 9 3 3 6]
  [1 6 4 5 3]
  [5 0 6 2 7]]

 [[3 9 7 6 3]
  [5 8 0 9 2]
  [2 0 6 0 9]
  [6 3 2 2 1]]]
4
[[[[4 0 7 1 5]
   [9 6 8 5 2]
   [0 9 4 3 6]
   [0 8 9 8 2]]

  [[9 7 1 6 3]
   [7 4 2 5 8]
   [6 3 7 9 7]
   [8 0 7 1 1]]

  [[9 0 4 1 4]
   [6 8 2 2 4]
   [0 8 4 5 8]
   [0 2 3 7 7]]]


 [[[5 0 8 8 6]
   [0 0 0 3 7]
   [4 6 3 1 1]
   [5 6 1 4 7]]

  [[7 8 6 8 8]
   [7 7 1 6 9]
   [3 0 3 7 3]
   [8 1 8 2 7]]

  [[4 4 4 2 4]
   [5 1 7 6 4]
   [6 0 5 3 9]
   [0 0 0 9 6]]]


 [[[9 2 7 9 6]
   [9 1 9 0 1]
   [4 6 3 3 7]
   [8 6 9 3 7]]

  [[2 4 0 6 1]
   [5 4 6 5 3]
   [3 9 0 7 6]
   [5 8 5 4 6]]

  [[5 2 6 5 0]
   [7 8 0 0 0]
   [2 1 2 9 4]
   [3 8 9 4 1]]]]


In [64]:
# find dimension of matrix

arr = [[1,2,3],[4,5,6],[7,8,9]]
n = np.array(arr)
print(n.ndim)
print(n.shape)
print(n.size)


2
(3, 3)
9


In [66]:
#it is used to concatenate array
np.concatenate([n,n])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
#it is used to concatenate array
np.concatenate([n,n],1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [ ]:
#